project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true
files:
  - source: ui/src/commonMain/moko-resources/base/plurals.xml
    translation: ui/src/commonMain/moko-resources/%locale%/plurals.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings_auth.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings_auth.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings_explore.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings_explore.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings_explorer.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings_explorer.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings_home.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings_home.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings_profile.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings_profile.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings_release.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings_release.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings_repository.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings_repository.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/

  - source: ui/src/commonMain/moko-resources/base/strings_settings.xml
    translation: ui/src/commonMain/moko-resources/%locale%/strings_settings.xml
    ignore:
      - ui/src/commonMain/moko-resources/images/
      - ui/src/commonMain/moko-resources/files/