name: Sync GraphQL Schema

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/gqlsync.yml'
      - 'api/build.gradle.kts'
  schedule:
    - cron: "0 17 * * 5" # "At 17:00 on Friday."
  workflow_dispatch:

jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Download Schema via Introspection
        run: |
          chmod +x ./gradlew && ./gradlew :api:downloadServiceApolloSchemaFromIntrospection
        env:
          GLOOM_INTROSPECTION_TOKEN: ${{ secrets.GLOOM_INTROSPECTION_TOKEN }}

      - name: Push
        run: |
          sudo chmod -R ugo+rwX .
          git add *
          git commit -m "chore(api/graphql): Sync GraphQL Schema"
          git push origin main
